---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-otc-kustomize-cm
data:
  cluster_name: yfb-ext-prd
  cluster_index: "2"
  vault_address: https://vault.yolt.io
  main_namespace: ycs
  namespace_prefix: ycs_
