---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: $(POD_NAMESPACE)
commonLabels:
  jobs.kubernetes.io/name: "kubernetes-otc-curl"
  app.kubernetes.io/managed-by: "kubernetes-otc"
bases:
- ../../../env/management-dta
- ../../../type/curl
- ../../../service
