---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: kubernetes-otc-query-sql
  files:
  - query.sql
generatorOptions:
  disableNameSuffixHash: true
bases:
- ../../../base/
patchesStrategicMerge:
- patch.yaml
nameSuffix: -postgres
