apiVersion: batch/v1
kind: Job
metadata:
  name: kubernetes-otc
spec:
  backoffLimit: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-secret-psql.sh: $(ENVIRONMENT_NAME)/database/$(RDS_INSTANCE_NAME)/creds/$(DATABASE_NAME)
        vault.hashicorp.com/agent-inject-template-psql.sh: |
          {{- with secret "$(ENVIRONMENT_NAME)/database/$(RDS_INSTANCE_NAME)/creds/$(DATABASE_NAME)" -}}
          #!/bin/bash
          PGDATABASE=$(DATABASE_NAME) PGHOST=$(RDS_HOSTNAME_PREFIX).$(ENVIRONMENT_NAME).yolt.io PGPORT=5432 PGUSER={{- .Data.username }} PGPASSWORD={{- .Data.password }} psql -f /queries/query.sql
          {{- end }}
    spec:
      containers:
      - args:
        - -c
        - "if [[ $(date +'%m/%d/%Y') != '$(EXECUTION_DATE)' ]] ; then echo 'wrong date to execute job' && exit 1000; fi; /bin/bash /vault/secrets/psql.sh;"
        command:
        - /bin/bash
        image: 627987680837.dkr.ecr.eu-central-1.amazonaws.com/prd/sre/postgres:14.1-637348
        name: kubernetes-otc
        volumeMounts:
        - mountPath: /queries
          name: queries
      volumes:
      - configMap:
          name: kubernetes-otc-query-sql-postgres
        name: queries
