---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: kubernetes-otc-query-sql
    files:
      - script.sh
generatorOptions:
  disableNameSuffixHash: true
bases:
- ../../../base/
patchesStrategicMerge:
- patch.yaml
nameSuffix: -postgres-bash
