apiVersion: batch/v1
kind: Job
metadata:
  name: kubernetes-otc
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-pre-populate: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-run-as-same-user: "true"
        vault.hashicorp.com/agent-limits-cpu: "100m"
        vault.hashicorp.com/agent-limits-mem: "128Mi"
        vault.hashicorp.com/agent-requests-cpu: "10m"
        vault.hashicorp.com/agent-requests-mem: "24Mi"
        vault.hashicorp.com/auth-path: auth/$(ENVIRONMENT_NAME)/k8s/eks/pods/$(POD_NAMESPACE)
        vault.hashicorp.com/role: $(MICROSERVICE_NAME)
    spec:
      containers:
        - name: kubernetes-otc
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsGroup: 999
            runAsNonRoot: true
            runAsUser: 999
      restartPolicy: Never
      serviceAccount: $(MICROSERVICE_NAME)
